### ISSUE TITLE
Wrong Escaped Characters

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [zspitz/ExpressionTreeToString#88] opened 2021-12-23 17:01 UTC
I'm currently trying the example from the main page:

```
            Expression<Func<Person, bool>> filter = p => p.LastName == "A" || p.FirstName == "B" || p.DOB == DateTime.MinValue || p.LastName == "C" || p.FirstName == "D";
            Console.WriteLine(filter.ToString("Dynamic LINQ", "C#")); 
```
And the output differs from the example, it's gaining an "/" character for escaping character
But this is causing exceptions when trying to convert back to an expression

That's my output:
"LastName in (\"A\", \"C\") || FirstName in (\"B\", \"D\") || DOB == DateTime.MinValue"

The quotes are really included there, which should not.
Perhaps an screenshot from my console explain it better:
![image](https://user-images.githubusercontent.com/85890187/147271281-05bb2b5a-f6c8-4bee-b76d-86a5bd7ea18f.png)

**Comment by zspitz** [comment] 2021-12-24 00:13
This behavior is intentional. The idea is to be able to paste the corresponding Dynamic LINQ string directly into C# or VB.NET, where the escaping would be necessary. In other words, you should be able to copy the text from the console window directly into C#.

If you specifically need the unescaped string, there are a few options.

The simplest: this behavior is only on expressions that are wrapped in `LambdaExpression`s; otherwise the resultant string is unescaped. In other words:

```csharp
Console.WriteLine(filter.Body.ToString("Dynamic LINQ", "C#"));
```

would print:

```none
it.LastName in ("A", "C") || it.FirstName in ("B", "D") || it.DOB == DateTime.MinValue
```

Or, you could just call `Console.WriteLine` passing in the string, in code, or in the C# Interactive window:

```none
> Console.WriteLine("LastName in (\"A\", \"C\") || FirstName in (\"B\", \"D\") || DOB == DateTime.MinValue")
LastName in ("A", "C") || FirstName in ("B", "D") || DOB == DateTime.MinValue
```

---

Moving forward, I should update the README.

Also, currently the formatter requires the language parameter to know how to escape. I would consider making it optional, and in that case, returning the unescaped string.

**Comment by zspitz** [comment] 2021-12-24 06:18
Just wanted to add: I decided to include the escape sequences because an expression tree can contain calls to `Where`, `Select` or other LINQ methods; in fact every `IQueryable` consists of an expression tree.

```csharp
IQueryable<Person> query = new List<Person>()
    .AsQueryable()
    .Where(p => p.LastName == "A" || p.FirstName == "B" || p.DOB == DateTime.MinValue || p.LastName == "C" || p.FirstName == "D");
Console.WriteLine(query.Expression.ToString("Dynamic LINQ", "C#"));
/*
    #EnumerableQuery<Person>.Where("LastName in (\"A\", \"C\") || FirstName in (\"B\", \"D\") || DOB == DateTime.MinValue")
*/
```
The result is (or looks something like) executable code, which requires the escape sequence.

**Comment by zspitz** [comment] 2022-01-08 23:20
Closing this as by design.

**Closed as completed by zspitz** 2022-01-08 23:20 UTC
Labels: bug, wontfix
